# Generated by Django 3.0.7 on 2020-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200613_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
